### ISSUE TITLE
scrubber_bfs.py error

### ISSUE THREAD

**Issue by JIBINJOHNV** [TGatter/LazyBastard#3]
I was trying to use the software but facing some issues. Error message I got is given below.  Can you please help me with this?.

[M::worker_pipeline::2896.250*2.92] mapped 2720 sequences
[M::worker_pipeline::2986.143*2.86] mapped 172527 sequences
[M::worker_pipeline::2987.402*2.86] mapped 2720 sequences
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -k15 -DP --dual=yes --no-long-join -w5 -m100 -g10000 -r2000 --max-chain-skip 25 --split-prefix foo /data/Nanopore_Data/PoreChop/RedSanders_PoreChop.fq.gz /data/tmp.VAoBBNSIzO/unitigs_corrected.fa
[M::main] Real time: 2988.549 sec; CPU: 8540.781 sec; Peak RSS: 47.715 GB
Traceback (most recent call last):
  File "/data/Software_Resources/LazyB/scrubber_bfs.py", line 22, in <module>
    seq_dict = SeqIO.index_db(seq_file_base+".idx", seq_file_base, "fastq")
  File "/home/cdfd/anaconda3/envs/DenovoGenome/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 964, in index_db
    index_filename, filenames, proxy_factory, format, key_function, repr
  File "/home/cdfd/anaconda3/envs/DenovoGenome/lib/python3.6/site-packages/Bio/File.py", line 311, in __init__
    self._load_index()
  File "/home/cdfd/anaconda3/envs/DenovoGenome/lib/python3.6/site-packages/Bio/File.py", line 328, in _load_index
    "SELECT value FROM meta_data WHERE key=?;", ("count",)
TypeError: 'NoneType' object is not iterable

>>>> Anchor Mapping
[M::mm_idx_gen::0.000*4.26] collected minimizers
[M::mm_idx_gen::0.002*3.19] sorted minimizers
[M::main::0.002*3.18] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.002*3.15] mid_occ = 1000000
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.002*3.11] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan; total length: 0
[M::worker_pipeline::3.749*2.47] mapped 172527 sequences
[M::worker_pipeline::3.772*2.47] mapped 2720 sequences
[M::worker_pipeline::4.948*2.13] mapped 172527 sequences
[M::worker_pipeline::4.948*2.13] mapped 2720 sequences
[M::main] Version: 2.21-r1071
[M::main] CMD: minimap2 -k15 -DP --dual=yes --no-long-join -w5 -m100 -g10000 -r2000 --max-chain-skip 25 --split-prefix foo /data//02_RedSanders_PoreChop.fq.gz.scrubbed.fa /data/tmp.VAoBBNSIzO/unitigs_corrected.fa
[M::main] Real time: 4.977 sec; CPU: 10.557 sec; Peak RSS: 0.979 GB
>>>> Lazy Bastard
  File "/data/Software_Resources/LazyB/prokrastinator.py", line 2343
    print "------------------- Graph "+str(i+1)+"/" + str(total)
                                     ^
SyntaxError: invalid syntax
cp: cannot stat '/data/tmp.VAoBBNSIzO/temp_1.target.fa': No such file or directory
>>>> Racon
[bioparser::createParser] error: unable to open file /data/tmp.VAoBBNSIzO/temp_1.query.fa!

**Comment by hangsuUNC** [comment]
I had the same issue, The error message shows as follows:

File "/home/suhang/lazyB/LazyB-master/unitig_filter.py", line 16, in <module>
    illumina_dict = SeqIO.index_db(unitigs + ".idx", unitigs, "fasta")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/site-packages/Bio/SeqIO/__init__.py", line 960, in index_db
    return _SQLiteManySeqFilesDict(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/site-packages/Bio/File.py", line 323, in __init__
    self._load_index()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/site-packages/Bio/File.py", line 351, in _load_index
    if self._length != int(count):
                       ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType


Any suggestions how to resolve this?
